name: Postman collection workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
  - cron: '30 05 * * *'  # Every day at 05:30 UTC

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4.1.2

      - name: Set up Node.js
        uses: actions/setup-node@v3.9.1
        with:
          node-version: '22'

      - name: Install Newman and htmlextra reporter globally
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run the Postman collection with Newman
        run: |
          newman run "Inwarranty_Flow_Collection_Jatin CSV Data.postman_collection.json"\
            -e QA.postman_environment.json \
            -d TestData.csv \
            -r cli,htmlextra\
            --reporter-htmlextra-export .newman/index.html
      
      - name: Upload Newman HTML report
        if: always()
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Newman Report
          path: newman/*.html 

      - name: Create github page branch
        if : always()
        uses :  peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token : ${{ secrets.GITHUB_TOKEN }}
          publish_dir: newman/
          
      - name : Send Email Notification
        if : always()
        uses :  dawidd6/action-send-mail@v5
        with:
          server_address : smtp.gmail.com
          server_port : 465
          username : ${{ secrets.GMAIL_USERNAME }}
          password : ${{ secrets.GMAIL_PASSWORD }}
          subject : API TEST REPORT -GitHub Actions
          to : ranjanimanuel@gmail.com
          from: ${{ secrets.GMAIL_USERNAME }}
          body : |
             Hi,
              Phoenix Inwarranty flow has been executed and the Report has been published and the url
              is :https://ranjanimanuel.github.io/InwarrantyFlowCollection/
              Thank you.
              RanjaniManuel.
             
          
          
